### ISSUE TITLE
[Feature Request]: Allow for Redstone Control with Infected Bookshelves

### ISSUE THREAD

**Issue by birbs2** [terrarium-earth/Experience-Obelisk#22]
### Is your feature request related to a problem?

Making XP farms with the infected bookshelves can't be turned off, and are laggy.

### Solution(s)

A solution to this is to allow redstone control to the bookshelves, and this could fix laggyness because it wouldn't have to stay on for long (because it's so fast).

### Describe alternatives you've considered

Another option to redstone control is have the bookshelves emit more experience, less often, to reduce lag.

### Mod Version

2.2.5

### Mod Loader Version

1.20.1 - 47.3.0

### Mod Loader

Forge

### Additional context

Sorry if this is already a feature, I am new to this mod so I might not quite know how it works. Thanks!

**Comment by cyanog3n** [comment]
I've been considering this myself actually. So far the plan is to:

1. Change the shift-right-click functionality with the staff of attunement to redstone control on / redstone control off rather than enabled / disabled as it currently is
2. add configuration settings that allow customization for the default orb values & default delay for all 3 kinds of bookshelves

I haven't had time recently to work on this mod unfortunately. Do let me know if you would like any other feature!
